/*
-- Query: 
-- Date: 2016-12-23 18:15
*/
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('kind','child',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('kinder','child',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('sohn','child','m');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('söhne','child','m');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('tochter','child','f');
/*INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('töchter','child','f');*/
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('eltern','parent',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('vater','parent','m');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('mutter','parent','f');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('geschwister','sibling',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('bruder','sibling','m');
/*INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('brüder','sibling','m');*/
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('schwester','sibling','f');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('schwestern','sibling','f');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('freund','friend','m');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('freundin','friend','f');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('mann','spouse','m');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('frau','spouse','f');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('ehemann','spouse','m');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('ehefrau','spouse','f');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('onkel','parentsibling','m');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('onkels','parentsibling','m');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('tante','parentsibling','f');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('tanten','parentsibling','f');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('neffe','siblingchild','m');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('neffen','siblingchild','m');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('nichte','siblingchild','f');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('nichten','siblingchild','f');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('cousin','cousin','m');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('vetter','cousin','m');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('cousins','cousin','m');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('vettern','cousin','m');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('cousine','cousin','f');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('base','cousin','f');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('cousinen','cousin','f');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('basen','cousin','f');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('großeltern','grandparent',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('opa','grandparent','m');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('opas','grandparent','m');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('großvater','grandparent','m');
/*INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('großväter','grandparent','m');*/
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('oma','grandparent','f');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('omas','grandparent','f');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('großmutter','grandparent','f');
/*INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('großmütter','grandparent','f');*/
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('enkel','grandchild','m');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('enkelin','grandchild','f');
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`) VALUES ('enkelinnen','grandchild','f');
