/*
-- Query: 
-- Date: 2016-12-23 18:15
*/
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('kind','child',NULL,1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('kinder','child',NULL,NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('sohn','child','m',1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('söhne','child','m',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('tochter','child','f',1);
/*INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('töchter','child','f',NULL);*/
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('eltern','parent',NULL,1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('vater','parent','m',1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('mutter','parent','f',1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('geschwister','sibling',NULL,1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('bruder','sibling','m',1);
/*INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('brüder','sibling','m',NULL);*/
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('schwester','sibling','f',1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('schwestern','sibling','f',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('freund','friend','m',1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('freundin','friend','f',1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('mann','spouse','m',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('frau','spouse','f',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('ehemann','spouse','m',1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('ehefrau','spouse','f',1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('onkel','parentsibling','m',1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('onkels','parentsibling','m',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('tante','parentsibling','f',1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('tanten','parentsibling','f',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('neffe','siblingchild','m',1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('neffen','siblingchild','m',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('nichte','siblingchild','f',1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('nichten','siblingchild','f',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('cousin','cousin','m',1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('vetter','cousin','m',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('cousins','cousin','m',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('vettern','cousin','m',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('cousine','cousin','f',1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('base','cousin','f',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('cousinen','cousin','f',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('basen','cousin','f',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('großeltern','grandparent',NULL,1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('opa','grandparent','m',1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('opas','grandparent','m',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('großvater','grandparent','m',NULL);
/*INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('großväter','grandparent','m',NULL);*/
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('oma','grandparent','f',1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('omas','grandparent','f',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('großmutter','grandparent','f',NULL);
/*INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('großmütter','grandparent','f',NULL);*/
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('enkel','grandchild','m',1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('enkelin','grandchild','f',1);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('enkelinnen','grandchild','f',NULL);
INSERT INTO `member_rel_dict_de` (`relname`,`relation`,`gender`,`prio`) VALUES ('enkelkinder','grandchild',NULL,NULL);
